settings:
  title: 'Status Page'
  url: 'https://status.jackmerrill.com' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: mainsite
    name: jackmerrill.com
    url: 'https://jackmerrill.com/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: bitwarden
    name: Bitwarden Server
    url: 'https://bitwarden.jackmerrill.com'
    method: GET
    expectStatus: 200
    linkable: false

  - id: speedtest
    name: Speedtest Tracker
    url: 'https://speedtest.jackmerrill.com'
    method: GET
    expectStatus: 200
    linkable: true

  - id: jackflix
    name: Jackflix
    description: 'IYKYK'
    url: 'https://jelly.jackmerrill.com'
    method: GET
    expectStatus: 200
    linkable: false

  - id: jackflix-request
    name: Jellyseer
    url: 'https://request.jackmerrill.com'
    method: GET
    expectStatus: 200
    linkable: false
  
  - id: jackflix-invite
    name: Wizard
    url: 'https://wiz.jackmerrill.com'
    method: GET
    expectStatus: GET
    linkable: false
